apiVersion: kubernetes.dask.org/v1
kind: DaskJob
metadata:
  name: simple-job
  namespace: default
spec:
  job:
    spec: # PodSpec, standard k8s pod
      containers:
      - name: dask-demo
        image: dask-demo:alputer
        imagePullPolicy: Never
        volumeMounts:
        - name: my-volume
          mountPath: /app/output
        command: ["/bin/sh", "-c"]
        args:
          - exec python demo.py
      volumes:
      - name: my-volume
        hostPath:
          path: /home/logs
      restartPolicy: Never

  cluster:
    spec:
      worker:
        replicas: 0
        spec:
          containers:
            - name: worker
              image: "ghcr.io/dask/dask:2024.1.0"
              imagePullPolicy: "IfNotPresent"
              args:
                - dask-worker
                - --name
                - $(DASK_WORKER_NAME)
                - --dashboard
                - --dashboard-address
                - "8788"
              ports:
                - name: http-dashboard
                  containerPort: 8788
                  protocol: TCP
              env:
                - name: WORKER_ENV
                  value: hello-world # We dont test the value, just the name
              volumeMounts:
              - name: my-volume
                mountPath: /app/output
          volumes:
          - name: my-volume
            hostPath:
              path: /home/logs
      scheduler:
        spec:
          containers:
            - name: scheduler
              image: "ghcr.io/dask/dask:2024.1.0"
              imagePullPolicy: "IfNotPresent"
              args:
                - dask-scheduler
              ports:
                - name: tcp-comm
                  containerPort: 8786
                  protocol: TCP
                - name: http-dashboard
                  containerPort: 8787
                  protocol: TCP
              readinessProbe:
                httpGet:
                  port: http-dashboard
                  path: /health
                initialDelaySeconds: 5
                periodSeconds: 10
              livenessProbe:
                httpGet:
                  port: http-dashboard
                  path: /health
                initialDelaySeconds: 15
                periodSeconds: 20
              env:
                - name: SCHEDULER_ENV
                  value: hello-world
        service:
          type: ClusterIP
          selector:
            dask.org/cluster-name: simple-job
            dask.org/component: scheduler
          ports:
            - name: tcp-comm
              protocol: TCP
              port: 8786
              targetPort: "tcp-comm"
            - name: http-dashboard
              protocol: TCP
              port: 8787
              targetPort: "http-dashboard"