# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dask-demo
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/logs" # Path on the host
---
# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dask-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi